app = "alexvpn"
kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  max-per-region = 1
  strategy = "rolling"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = false
  private_network = true

[[services]]
  internal_port = 41641
  protocol = "udp"

  [[services.ports]]
    port = "41641"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"
